- LICENSE.md
- README.md
- pom.xml
- src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
- src/main/java/io/github/townyadvanced/townycombat/commands/TownyCombatAdminCommand.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
- src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
- src/main/java/io/github/townyadvanced/townycombat/tasks/JumpReductionTask.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
This PR adds tactical speed and damage adjustments:
- Infantry encumbrance/slowing due to armour
- Increases tactical options on the battlefield.
- Makes room for the development of practical military uniforms.
- Details:
```
- Military Equipment reduces walking speeds:
- Equipment:
- Shield: -4 %
- Full Leather Set: -4 %
- Full Chainmail Set: -8 %
- Full Iron Set: -16 %
- Full Gold Set: -20 %
- Full Diamond Set: -24 %    (*Walking around literally covered in rocks...*)
- Full Netherite Set: -28 %
- Players with 8% encumbrance or more are extra slow at jumping/climbing.
- This feature increases tactical options on the battlefield.
- This feature also allows nation to develop practically useful military uniforms.
- Full diamond/netherite sets are no longer de-rigeur, due to their tactical …
```
> Tactical Speed & Damage Adjustments

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- With current code charge does not go into cooldown on hit
- This PR fixes the issue
____
N/A
____
N/A
____
- [ N/A ] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the TownyCombat [License](https://github.com/TownyAdvanced/TownyCombat/blob/master/LICENSE.md) for perpetuity.
> Charge Fix - go into cooldown on hit

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
> Cav charge bugfix

- src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
- src/main/java/io/github/townyadvanced/townycombat/utils/Messaging.java
Before:
```
[11:02:53] [Server thread/INFO]: [TownyCombat] Enabling TownyCombat v0.2.0
[11:02:53] [Server thread/INFO]: [TownyCombat] =================================================================================
[11:02:53] [Server thread/INFO]: [TownyCombat] 
[11:02:53] [Server thread/INFO]: [TownyCombat]   *   )                             (                    )           )
[11:02:53] [Server thread/INFO]: [TownyCombat] ` )  /(     (  (           (        )\           )    ( /(     )  ( /( 
[11:02:53] [Server thread/INFO]: [TownyCombat]  ( )(_))(   )\))(    (     )\ )   (((_)   (     (     )\()) ( /(  )\()) 
[11:02:53] [Server thread/INFO]: [TownyCombat] (_(_()) )\ ((_)()\   )\ ) (()/(   )\___   )\    )\  '((_)\  )(_))(_))/  
[11:02:53] [Server thread/INFO]: [TownyCombat] |_ …
```
> Improve the look of the ascii art.

- pom.xml
- src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
- src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
- As per Illumineet's request, added support for using the custom model data ID to ID the new items.
N/A
____
Closes #52 
____
- [ x ] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the TownyCombat [License](https://github.com/TownyAdvanced/TownyCombat/blob/master/LICENSE.md) for perpetuity.
> Custom model data support

- README.md
Introduced in 18636d9fe9340a11c57b4a7c333a799488a86648.
Yeah, I know, it's a life-changing PR, no needs to thanks me!
> chore(README.md): fix typo

- pom.xml
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
- src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
- src/main/java/io/github/townyadvanced/townycombat/tasks/TownyCombatTask.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatMovementUtil.java
- Fixed bug where damage was lower than expected (issue in EntityDamageEntity listener)
- Added isEncumbraceEnabled config, & put some features behind that
- Cleaned up a few typos in config file
```
ENCUMBRANCE_ENABLED(
"encumbrance.enabled",
"true",
"",
"# If true, encumbrance is enabled."),
```
____
N / A
____
- [  ] I have tested this pull request for defects on a server. 
- Will get this tested before merging though
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the TownyCombat …
> Misc Fixes & Improvements

- pom.xml
- src/main/java/io/github/townyadvanced/townycombat/TownyCombat.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/metadata/TownyCombatResidentMetaDataController.java
Also fix up unused imports/errors.
> Update Min. Towny Version to 0.98.4.0.

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
When we prevent their rearing we stop the natural system that would keep the damage in check.
Closes #62.
> Prevent contact and fire causing excessive damage to horses.

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatStatusScreenListener.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatBattlefieldRoleUtil.java
- src/main/resources/lang/en-US.yml
- This PR adds the rest of the "Medium" role, except for the super potion
- Adds a small bit for the "Heavy" role also
> Finished adding medium, except for super potion

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatBattlefieldRoleUtil.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatHorseUtil.java
- src/main/resources/lang/en-UK.yml
- src/main/resources/lang/en-US.yml
- If player mounts a horse, horse armour now gets validated
- Horses now get passive effect changes
- Horses with heavy armour now get heavy effects
Closes #79
> Integrated horses with battlefield roles

- src/main/java/io/github/townyadvanced/townycombat/events/BattlefieldRole.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatStatusScreenListener.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/metadata/TownyCombatResidentMetaDataController.java
- src/main/java/io/github/townyadvanced/townycombat/settings/ConfigNodes.java
- src/main/java/io/github/townyadvanced/townycombat/settings/TownyCombatSettings.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatBattlefieldRoleUtil.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
- src/main/resources/lang/en-US.yml
- Added the granting of Super potions
- This is the whole first release Super-Potions feature, except for the potion-owner-restriction, and the potion-expiry-cleanups, which I will add in the next PR's
Tested: yes
> Battlefield Roles: Added Super-Potion granting

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatItemUtil.java
- src/main/resources/lang/en-US.yml
- Added the owner feature to super potions
- Each super potion has an owner
- Only the owner can use that super potion
- Also added some small bits of expiry date. That feature will be completed in an upcoming PR
> Battlefield Roles:  Add Super Potion Owners

- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatBattlefieldRoleUtil.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatHorseUtil.java
- src/main/resources/lang/en-US.yml
Fix the placeholder messages
Closes #111
> Fixed placeholder messages

- src/main/resources/lang/en-UK.yml
> Added uk file

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatBattlefieldRoleUtil.java
- Added code so that if mounted light/heavy cavalry drink their super potion, the horse gets the effect also
Closes #114
> Battlefield Roles: Apply super potion effects to horses

- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatBattlefieldRoleUtil.java
> Restrict Crossbow for Heavy Cavalry - they must be mounted

- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatBattlefieldRoleUtil.java
- src/main/java/io/github/townyadvanced/townycombat/utils/TownyCombatHorseUtil.java
- src/main/resources/lang/en-US.yml
Fisc Fixes following on from regression testing
Tested
Closes #82
> Misc fixes from regression testing

- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatBukkitEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatNationEventListener.java
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownEventListener.java
> Re-add ignore-cancelled = true to listeners.

- pom.xml
- src/main/java/io/github/townyadvanced/townycombat/listeners/TownyCombatTownyEventListener.java
> Fix scaffolds being used to glitch upwards.
